### ISSUE TITLE
HOME画面の実装

### ISSUE THREAD

**Issue by kubo-hide-kun** [Conken-NitKit/hackz-COVID#11]
## Overview (Required)
- UIは未完成ですが，構成はほとんど変わんないです

## Links
-

## Screenshot
<img src="https://user-images.githubusercontent.com/41711771/80665988-f289b680-8ad5-11ea-8da5-404b1e8ff502.png" width="300" />

**Comment by FukeKazki** [comment]
@kubo-hide-kun 
画面中央のカラー(灰色の部分)はどうしたらいいですか？
ダークモード ↓
https://gyazo.com/ba104fea91d2cf434003828401e5fd0b
ライトモード ↓
https://gyazo.com/95ba1bd4a41647c27a6fa12a0739562f

**Comment by kubo-hide-kun** [comment]
現状やってもらってるようにカラーコードの直接指定でお願いします🙏
